---
abstract: "show server status like Apache's mod_status"
author:
  - 'Masahiro Nagano <kazeburo {at} gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
  Test::TCP: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-Middleware-ServerStatus-Lite
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Net::CIDR::Lite: 0
  Parallel::Scoreboard: 0.02
  Plack::Middleware: 0
  Try::Tiny: 0.09
  parent: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/kazeburo/Plack-Middleware-ServerStatus-Lite.git
version: 'y'
